# print("How old are you?",)
# age = raw_input()
# print("How tall are you?",)
# height = raw_input()
# print("How much do you weigh?",)
# weight = raw_input()
age = int(input("How old are you?"))
height = input("How tall are you?")
weight = input("How much do you weigh?")

print("So, you're %r old, %r tall and %r heavy." % (age, height, weight))